apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod
  namespace: default
spec:
  containers:
    - name: cleanup
      image: busybox
      command:
        - "sleep"
        - "3600"  # 让 Pod 持续运行，以便你能进入进行操作
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /mnt/mysql-data
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
