name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t roderickyoung/shop-ease:mall-admin mall-admin
          docker build -t roderickyoung/shop-ease:mall-auth mall-auth
          docker build -t roderickyoung/shop-ease:mall-monitor mall-monitor
          docker build -t roderickyoung/shop-ease:mall-search mall-search
          docker build -t roderickyoung/shop-ease:mall-portal mall-portal
          docker build -t roderickyoung/shop-ease:mall-gateway mall-gateway
          

      - name: Push Docker image
        run: |
          docker push roderickyoung/shop-ease:mall-admin
          docker push roderickyoung/shop-ease:mall-auth
          docker push roderickyoung/shop-ease:mall-monitor
          docker push roderickyoung/shop-ease:mall-search
          docker push roderickyoung/shop-ease:mall-portal
          docker push roderickyoung/shop-ease:mall-gateway